[README.md] fix typo
SSL-Roots/consai2r2 pull request #57
Opened 2019-12-27 06:35 UTC by future731

2019-12-30 06:00 UTC, ShotaAk requested changes

2019-12-30 06:00 UTC, ShotaAk commented on README.md
> +[CONTIRIBUTING.md](./CONTRIBUTING.md)を見てくれると嬉しいです。
Fix typo の fix typoです

```diff
- [CONTIRIBUTING.md](./CONTRIBUTING.md)を見てくれると嬉しいです。
+ [CONTRIBUTING.md](./CONTRIBUTING.md)を見てくれると嬉しいです。
```

2020-01-01 12:05 UTC, future731 commented on README.md
> +[CONTIRIBUTING.md](./CONTRIBUTING.md)を見てくれると嬉しいです。
fixed

2020-01-01 12:08 UTC, ShotaAk approved these changes

2020-01-03 06:15 UTC, merged